### ISSUE TITLE
Request new version

### ISSUE THREAD

**Issue by Viro-Neo** [MartinFillon/epiheader#4]
The plugin is not supported anymore because of the new version of CLion. Incompatibility with the new build.

**Comment by MartinFillon** [comment]
Im gonna have a look its not normal cause i didnt have a notification from jetbrains

**Comment by MartinFillon** [comment]
![image](https://user-images.githubusercontent.com/114775771/228839259-8829cdda-b45b-4bf5-a1fb-bfb5ecc27975.png)
After verification with jetbrains everything is compatible, can you please describe your issue so that I work on it.

**Comment by Viro-Neo** [comment]
![Screenshot_20230330_144850](https://user-images.githubusercontent.com/91688796/228842202-0c09c1d9-bf22-4fb1-a927-8b2650fccd77.png)
Here's a screenshot of my IDE right now, I have restarted it already but the error is always here.

**Comment by MartinFillon** [comment]
Really strange im gonna investigate

**Comment by MartinFillon** [comment]
The fix is pushed, it was just a version match error as jetbrains doesnt support latest and make it like this so you review your plugin everytime.
